# Generated by Django 5.2 on 2025-09-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="steam_account_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
