# Generated by Django 5.2 on 2025-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_steam_account_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="realname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
