# Generated by Django 5.2 on 2025-12-13 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_realname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="steam_account_created_at",
            new_name="steam_user_since",
        ),
    ]
