# Generated by Django 5.2 on 2025-06-23 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("app_id", models.CharField(max_length=65, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("rating", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("genres", models.ManyToManyField(related_name="games", to="core.genre")),
            ],
        ),
        migrations.CreateModel(
            name="UserGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("total_playtime", models.IntegerField(default=0)),
                ("recent_playtime", models.IntegerField(default=0)),
                ("last_played", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.game"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-last_played"],
                "unique_together": {("user", "game")},
            },
        ),
    ]
