# Generated by Django 5.2 on 2025-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="games", to="core.genre"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
