# Generated by Django 5.2 on 2025-10-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_game_genres_alter_game_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(blank=True, related_name="games", to="core.genre"),
        ),
    ]
