# Generated by Django 5.2 on 2026-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_game_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
