# Generated by Django 5.2 on 2026-01-29 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_game_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="price",
        ),
    ]
