# Generated by Django 5.2 on 2026-01-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_theme_game_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="igdb_id",
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
