# Generated by Django 5.2 on 2026-02-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_theme_igdb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="header_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
