# Generated by Django 5.2 on 2026-02-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_game_header_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="time_to_beat",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
