# Generated by Django 5.2 on 2026-02-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_game_time_to_beat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="time_to_beat",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
