# Generated by Django 5.2 on 2026-02-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_game_rating_alter_game_time_to_beat"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("service_name", models.CharField(max_length=32, unique=True)),
                ("access_token", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
        ),
    ]
